import { StyleSheet } from "react-native";
import stylesConfig from "../../config.styles";

export const loginPageStyles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: stylesConfig.colors.default_background,
    paddingVertical: 20,
  },
  returnIconContainer: {
    width: "100%",
    paddingHorizontal: 20,
  },
  returnIcon: {
    width: 40,
    color: stylesConfig.colors.default_color_2,
  },
  form: {
    gap: 10,
    flex: 1,
    width: "80%",
    minHeight: "70%",
    alignItems: "center",
    justifyContent: "center",
  },
  formTitle: {
    width: "100%",
    fontSize: 27,
    color: stylesConfig.colors.default_color_2,
    fontWeight: "600",
    textAlign: "left",
  },
  formSubTitle: {
    width: "100%",
    fontSize: 14,
    color: stylesConfig.colors.default_color_1,
    fontWeight: "600",
    textAlign: "left",
    marginLeft: "2%",
  },
  inputContainer: {
    minWidth: "100%",
    maxWidth: "100%",
    maxHeight: 40,
    overflow: "scroll",
    marginVertical: 5,

    flex: 1,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",

    padding: 5,
    borderBottomColor: stylesConfig.colors.default_color_1,
    borderStartColor: stylesConfig.colors.default_background,
    borderBottomWidth: 1,
  },
  textInput: { width: "100%" },
  icon: {
    alignSelf: "center",
    alignItems: "center",
    width: 40,
    color: stylesConfig.colors.default_color_2,
  },
  logo: {
    maxHeight: 120,
    width: "100%",
    resizeMode: "contain",
  },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    marginTop: 10,
    height: 50,
    borderRadius: 2,
    backgroundColor: stylesConfig.colors.default_color_3,
    elevation: 10,
  },
  buttonText: {
    alignContent: "center",
    width: "100%",
    fontSize: 27,
    color: stylesConfig.colors.default_background,
    fontWeight: "600",
    textAlign: "center",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    flexDirection: "row",
    gap: 5,
  },
  footerTextBold: {
    fontSize: 16,
    color: stylesConfig.colors.default_color_4,
    fontWeight: "600",
    textAlign: "center",
  },
  socialMedia: {
    width: "100%",
    height: 100,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  socialMediaTitle: {
    marginTop: 20,
    fontSize: 12,
    color: stylesConfig.colors.default_color_1,
    fontWeight: "600",
    textAlign: "center",
  },
  socialMediaIcon: {
    borderColor: stylesConfig.colors.default_color_4,
    borderWidth: 2,
    width: 50,
    height: 50,
    borderRadius: 10,
    display: "flex",
    textAlign: "center",
    textAlignVertical: "center",
    color: stylesConfig.colors.default_color_4,
    backgroundColor: stylesConfig.colors.default_background,
    elevation: 7,
  },
});
